"""added unique constraint on username

Revision ID: 00716459cd7d
Revises: 798bb8352cbf
Create Date: 2017-07-20 20:23:34.911286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00716459cd7d'
down_revision = '798bb8352cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_uc', 'user', ['name'], schema='bsg_info')
    op.create_unique_constraint(None, 'user', ['name'], schema='bsg_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='bsg_info', type_='unique')
    op.drop_constraint('name_uc', 'user', schema='bsg_info', type_='unique')
    # ### end Alembic commands ###
