"""alembic messed up a ton

Revision ID: 11feb46c6200
Revises: e0a83be84c7a
Create Date: 2017-07-26 18:14:06.805928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11feb46c6200'
down_revision = 'e0a83be84c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('humans')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('cylons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cylons',
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'user_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('game',
    sa.Column('loss_condition', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('raptors_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('vipers_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('fuel_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('food_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('morale_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('population_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('distance_left', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('humans',
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'user_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
