"""add game

Revision ID: 35ae8d4efa5c
Revises: 6d7cd05e7539
Create Date: 2017-07-20 09:28:46.527987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ae8d4efa5c'
down_revision = '6d7cd05e7539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loss_condition', sa.SMALLINT(), nullable=False),
    sa.Column('raptors_left', sa.SMALLINT(), nullable=True),
    sa.Column('vipers_left', sa.SMALLINT(), nullable=True),
    sa.Column('fuel_left', sa.SMALLINT(), nullable=True),
    sa.Column('food_left', sa.SMALLINT(), nullable=True),
    sa.Column('morale_left', sa.SMALLINT(), nullable=True),
    sa.Column('population_left', sa.SMALLINT(), nullable=True),
    sa.Column('distance_left', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bsg_info',
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game', schema='bsg_info')
    # ### end Alembic commands ###
