"""removed redundant unique constraint

Revision ID: 94ba0817bee4
Revises: 00716459cd7d
Create Date: 2017-07-20 23:37:55.879652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ba0817bee4'
down_revision = '00716459cd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
