"""remove on_delete column from users and games

Revision ID: 9f450115435d
Revises: c5fe63f2b143
Create Date: 2017-07-31 06:08:57.851968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f450115435d'
down_revision = 'c5fe63f2b143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'cylons_ibfk_1', 'cylon', type_='foreignkey')
    op.drop_constraint(u'cylons_ibfk_2', 'cylon', type_='foreignkey')
    op.create_foreign_key(None, 'cylon', 'game', ['game_id'], ['game_id'], source_schema='bsg_info', referent_schema='bsg_info', ondelete='CASCADE')
    op.create_foreign_key(None, 'cylon', 'user', ['user_id'], ['user_id'], source_schema='bsg_info', referent_schema='bsg_info')
    op.drop_column('game', 'is_deleted')
    op.drop_constraint(u'humans_ibfk_1', 'human', type_='foreignkey')
    op.drop_constraint(u'humans_ibfk_2', 'human', type_='foreignkey')
    op.create_foreign_key(None, 'human', 'user', ['user_id'], ['user_id'], source_schema='bsg_info', referent_schema='bsg_info')
    op.create_foreign_key(None, 'human', 'game', ['game_id'], ['game_id'], source_schema='bsg_info', referent_schema='bsg_info', ondelete='CASCADE')
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'human', schema='bsg_info', type_='foreignkey')
    op.drop_constraint(None, 'human', schema='bsg_info', type_='foreignkey')
    op.create_foreign_key(u'humans_ibfk_2', 'human', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(u'humans_ibfk_1', 'human', 'game', ['game_id'], ['game_id'])
    op.add_column('game', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cylon', schema='bsg_info', type_='foreignkey')
    op.drop_constraint(None, 'cylon', schema='bsg_info', type_='foreignkey')
    op.create_foreign_key(u'cylons_ibfk_2', 'cylon', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(u'cylons_ibfk_1', 'cylon', 'game', ['game_id'], ['game_id'])
    # ### end Alembic commands ###
