"""adding everything back

Revision ID: cf04f0dece49
Revises: 11feb46c6200
Create Date: 2017-07-26 18:14:40.040866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf04f0dece49'
down_revision = '11feb46c6200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('user_id', sa.INTEGER(), nullable=False, autoincrement=True),
        sa.Column('name', sa.VARCHAR(length=30), nullable=False),
        sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('name'),
        schema='bsg_info',
        mysql_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_table('game',
        sa.Column('game_id', sa.INTEGER(), nullable=False, autoincrement=True),
        sa.Column('date', sa.TIMESTAMP(), nullable=False),
        sa.Column('loss_condition', sa.SMALLINT(), nullable=False),
        sa.Column('raptors_left', sa.SMALLINT(), nullable=True),
        sa.Column('vipers_left', sa.SMALLINT(), nullable=True),
        sa.Column('fuel_left', sa.SMALLINT(), nullable=True),
        sa.Column('food_left', sa.SMALLINT(), nullable=True),
        sa.Column('morale_left', sa.SMALLINT(), nullable=True),
        sa.Column('population_left', sa.SMALLINT(), nullable=True),
        sa.Column('distance_left', sa.SMALLINT(), nullable=True),
        sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint('game_id'),
        schema='bsg_info',
        mysql_charset='utf8',
        mysql_engine='InnoDB'
    )
    op.create_table('cylons',
        sa.Column('game_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('game_id', 'user_id'),
        sa.ForeignKeyConstraint(['game_id'], ['game.game_id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id']),
        schema='bsg_info'
    )
    op.create_table('humans',
        sa.Column('game_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint('game_id', 'user_id'),
        sa.ForeignKeyConstraint(['game_id'], ['game.game_id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id']),
        schema='bsg_info'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='bsg_info')
    op.drop_table('game', schema='bsg_info')
    op.drop_table('cylons', schema='bsg_info')
    op.drop_table('humans', schema='bsg_info')
    # ### end Alembic commands ###
