"""renamed tables humans and cylons to human and cylon

Revision ID: cf0da8b2f4b3
Revises: cf04f0dece49
Create Date: 2017-07-26 19:44:07.009143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf0da8b2f4b3'
down_revision = 'cf04f0dece49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('humans')
    op.drop_table('cylons')
    op.create_table(
        'cylon',
        sa.Column('game_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], [u'game.game_id'], name=u'cylons_ibfk_1'),
        sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'cylons_ibfk_2'),
        sa.PrimaryKeyConstraint('game_id', 'user_id'),
        schema='bsg_info'
    )
    
    op.create_table(
        'human',
        sa.Column('game_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], [u'game.game_id'], name=u'humans_ibfk_1'),
        sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'humans_ibfk_2'),
        sa.PrimaryKeyConstraint('game_id', 'user_id'),
        schema='bsg_info'
    )  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human', schema='bsg_info')
    op.drop_table('cylon', schema='bsg_info')
    op.create_table(
        'cylons',
        sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['game_id'], [u'game.game_id'], name=u'cylons_ibfk_1'),
        sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'cylons_ibfk_2'),
        sa.PrimaryKeyConstraint('game_id', 'user_id'),
        mysql_default_charset=u'latin1',
        mysql_engine=u'InnoDB'
    )
    op.create_table(
        'humans',
        sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['game_id'], [u'game.game_id'], name=u'humans_ibfk_1'),
        sa.ForeignKeyConstraint(['user_id'], [u'user.user_id'], name=u'humans_ibfk_2'),
        sa.PrimaryKeyConstraint('game_id', 'user_id'),
        mysql_default_charset=u'latin1',
        mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
