"""suppored many to many relation between games and players

Revision ID: e0a83be84c7a
Revises: 849b3738589a
Create Date: 2017-07-25 19:06:50.901341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0a83be84c7a'
down_revision = '849b3738589a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cylons',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'user_id'),
    schema='bsg_info'
    )
    op.create_table('humans',
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'user_id'),
    schema='bsg_info'
    )
    op.add_column(u'game', sa.Column('date', sa.TIMESTAMP(), nullable=False))
    op.add_column(u'game', sa.Column('game_id', sa.INTEGER(), nullable=False))
    op.drop_column(u'game', 'id')
    op.add_column(u'user', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column(u'user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column(u'user', 'user_id')
    op.add_column(u'game', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column(u'game', 'game_id')
    op.drop_column(u'game', 'date')
    op.drop_table('humans', schema='bsg_info')
    op.drop_table('cylons', schema='bsg_info')
    # ### end Alembic commands ###
