"""fixed game primary key

Revision ID: e615221a721d
Revises: 35ae8d4efa5c
Create Date: 2017-07-20 09:29:35.710101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e615221a721d'
down_revision = '35ae8d4efa5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
